import { useMemo, useState } from "react";
import { snapshot } from "./_shared/snapshot";

type Stock = (typeof snapshot.stocks)[number];

const usd = (n: number | null, digits = 2) => n === null ? "—" : `$${n.toLocaleString("en-US", { minimumFractionDigits: digits, maximumFractionDigits: digits })}`;

function Signal({ state }: { state: Stock["state"] }) {
  const title = state === "fair" ? "Fair" : state === "elevated" ? "Elevated" : state === "dislocated" ? "Dislocated" : "Unpriced";
  return <span className={`bs-signal ${state}`}><i />{title}</span>;
}

function Plot() {
  const polyline = useMemo(() => {
    const items = snapshot.nvdaHistory;
    const low = Math.min(...items.map((item) => item.pool));
    const high = Math.max(...items.map((item) => item.pool));
    return items.map((item, index) => `${(index / (items.length - 1)) * 100},${88 - ((item.pool - low) / (high - low)) * 58}`).join(" ");
  }, []);
  return <div className="bs-plot">
    <div className="bs-level l1" /><div className="bs-level l2" /><div className="bs-level l3" />
    <svg viewBox="0 0 100 100" preserveAspectRatio="none"><line x1="0" x2="100" y1="52" y2="52" /><polyline points={polyline} /></svg>
    <div className="bs-legend"><span><b />Reference</span><span><b />Onchain</span></div>
  </div>;
}

export function BaseBlueSans() {
  const [chosen, setChosen] = useState<Stock>(snapshot.stocks[0]);
  const [term, setTerm] = useState("");
  const [result, setResult] = useState("");
  const results = snapshot.stocks.filter((item) => `${item.ticker} ${item.address}`.toLowerCase().includes(term.trim().toLowerCase()));

  return <main className="base-blue-sans">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wdth,wght@10..48,75..100,400..800&family=DM+Mono:wght@400;500&display=swap" />
    <style>{`
      .base-blue-sans{--base:#2454db;--ink:#17254a;--fog:#f3f5f9;--paper:#fbfbf8;--hair:#d6dce8;--ink-muted:#63708d;--sage:#4b886d;--ochre:#a6771c;--red:#bd6158;background:var(--paper);color:var(--ink);font-family:"Bricolage Grotesque",sans-serif;min-height:100dvh;letter-spacing:-.035em}.base-blue-sans *{box-sizing:border-box}.base-blue-sans button,.base-blue-sans input{font:inherit}.base-blue-sans button{cursor:pointer}
      .bs-hero{background:var(--base);color:#fff;padding:0 46px 0;position:relative;min-height:630px}.bs-hero:after{content:"";position:absolute;bottom:-1px;left:0;right:0;height:74px;background:var(--paper);clip-path:polygon(0 76%,61% 8%,100% 72%,100% 100%,0 100%)}.bs-nav{height:78px;border-bottom:1px solid rgba(255,255,255,.28);max-width:1188px;margin:auto;display:flex;align-items:center;position:relative;z-index:1}.bs-brand{display:flex;gap:10px;align-items:center;font-size:20px;font-weight:750;letter-spacing:-.065em}.bs-brand-mark{width:20px;height:20px;display:grid;grid-template-columns:repeat(3,1fr);gap:2px;align-items:end}.bs-brand-mark span{display:block;background:#fff}.bs-brand-mark span:nth-child(1){height:8px}.bs-brand-mark span:nth-child(2){height:17px}.bs-brand-mark span:nth-child(3){height:12px}.bs-links{display:flex;gap:30px;margin-left:70px}.bs-links button{padding:6px 0;border:0;background:none;color:#c3d2ff;font-size:13px}.bs-links button.active{color:#fff;border-bottom:1px solid #fff}.bs-updated{font-family:"DM Mono",monospace;margin-left:auto;font-size:10px;color:#d1dcff;display:flex;align-items:center;gap:7px;letter-spacing:-.05em}.bs-updated i{width:7px;height:7px;background:#c3e9ca;border-radius:100%}
      .bs-hero-grid{max-width:1188px;margin:auto;display:grid;grid-template-columns:41% 59%;gap:39px;padding-top:62px;position:relative;z-index:1}.bs-kicker{font-size:12px;color:#c7d5ff;font-weight:700;margin-bottom:20px}.bs-copy h1{font-size:60px;line-height:.94;letter-spacing:-.08em;margin:0;font-weight:700;max-width:435px}.bs-copy p{font-size:15px;line-height:1.5;color:#dae3ff;max-width:385px;margin:28px 0 24px;letter-spacing:-.025em}.bs-button{border:1px solid rgba(255,255,255,.5);background:transparent;color:#fff;padding:12px 15px;font-size:12px;font-weight:750;transition:background .18s,color .18s}.bs-button:hover{background:#fff;color:var(--base)}.bs-meta{font-family:"DM Mono",monospace;color:#b8caff;font-size:10px;line-height:1.65;letter-spacing:-.055em;margin-top:18px}
      .bs-card{background:#fff;color:var(--ink);border:1px solid rgba(15,39,112,.17);box-shadow:0 15px 0 rgba(19,45,127,.13);align-self:start;margin-right:0}.bs-card-top{display:flex;justify-content:space-between;align-items:center;padding:19px 20px;border-bottom:1px solid var(--hair)}.bs-token{display:flex;align-items:center;gap:10px}.bs-token-box{width:30px;height:30px;display:grid;place-items:center;background:var(--ink);color:#fff;font-size:10px;font-weight:800}.bs-token strong{font-size:15px}.bs-token small{display:block;font-size:11px;color:var(--ink-muted);margin-top:2px}.bs-source{font-family:"DM Mono",monospace;color:var(--sage);font-size:10px}.bs-numbers{display:grid;grid-template-columns:1fr 1fr 1fr;border-bottom:1px solid var(--hair)}.bs-cell{padding:17px 20px 16px;border-right:1px solid var(--hair)}.bs-cell:last-child{border:0}.bs-cell label,.bs-label{display:block;font-size:10px;color:var(--ink-muted);font-weight:700;margin-bottom:8px}.bs-cell output{font-family:"DM Mono",monospace;font-size:19px;letter-spacing:-.075em}.bs-cell:last-child output{color:var(--ochre)}.bs-plot{height:143px;margin:16px 20px 16px;position:relative;overflow:hidden}.bs-plot svg{position:absolute;inset:0;width:100%;height:100%;overflow:visible}.bs-plot line{stroke:#a8b1c4;stroke-width:.75;stroke-dasharray:1.5 1.5}.bs-plot polyline{fill:none;stroke:var(--base);stroke-width:1.6;vector-effect:non-scaling-stroke}.bs-level{position:absolute;left:0;right:0;border-top:1px solid #eef0f4}.bs-level.l1{top:25%}.bs-level.l2{top:52%}.bs-level.l3{top:79%}.bs-legend{position:absolute;right:0;bottom:0;display:flex;gap:13px;font-size:10px;color:var(--ink-muted)}.bs-legend span{display:flex;align-items:center;gap:4px}.bs-legend b{width:11px;border-top:1px dashed #98a1b7}.bs-legend span:last-child b{border-top:2px solid var(--base)}
      .bs-tape{max-width:1102px;margin:0 auto;padding:44px 0 74px;position:relative}.bs-tape-head{display:flex;align-items:end;justify-content:space-between;margin-bottom:18px}.bs-tape h2{font-size:30px;line-height:1;margin:0;letter-spacing:-.065em}.bs-summary{font-family:"DM Mono",monospace;color:var(--ink-muted);font-size:10px;letter-spacing:-.05em}.bs-table{border-top:2px solid var(--ink);border-bottom:1px solid var(--hair)}.bs-head,.bs-row{display:grid;grid-template-columns:1.35fr 1fr 1fr .75fr .78fr;align-items:center}.bs-head{height:37px;border-bottom:1px solid var(--hair);font-size:10px;font-weight:700;color:var(--ink-muted)}.bs-row{height:51px;border-bottom:1px solid var(--hair);font-size:12px;transition:background .18s}.bs-row:last-child{border-bottom:0}.bs-row:hover,.bs-row.selected{background:#eaf0ff}.bs-head>*,.bs-row>*{padding:0 11px}.bs-head>*:first-child,.bs-row>*:first-child{padding-left:0}.bs-row button{border:0;background:transparent;color:var(--ink);text-align:left;font-weight:800;font-size:12px;padding-left:0}.bs-row button span{font-weight:500;color:var(--ink-muted);font-size:11px;margin-left:9px}.bs-value{font-family:"DM Mono",monospace;font-size:11px;letter-spacing:-.06em}.bs-signal{display:inline-flex;gap:6px;align-items:center;font-size:11px;font-weight:700}.bs-signal i{width:6px;height:6px;background:var(--sage);border-radius:50%}.bs-signal.elevated{color:var(--ochre)}.bs-signal.elevated i{background:#d59b28}.bs-signal.dislocated{color:var(--red)}.bs-signal.dislocated i{background:var(--red)}.bs-signal.unpriced{color:#7d8698}.bs-signal.unpriced i{background:#aab2c3}
      .bs-verify{background:var(--fog);padding:41px 46px;border-top:1px solid #e1e5ee}.bs-verify-inner{max-width:1102px;margin:auto;display:grid;grid-template-columns:1fr 1.65fr;gap:66px;align-items:center}.bs-verify h2{font-size:27px;line-height:1;margin:0;letter-spacing:-.065em}.bs-form{display:flex;align-items:center;border-bottom:1px solid #9eabc7;padding-bottom:8px}.bs-form input{background:transparent;border:0;outline:0;flex:1;color:var(--ink);font-size:13px}.bs-form input::placeholder{color:#74809d}.bs-form button{border:0;background:var(--base);color:#fff;padding:10px 13px;font-size:11px;font-weight:750}.bs-answer{height:16px;color:var(--sage);font-size:11px;margin-top:7px}
      @media(max-width:800px){.bs-hero{padding:0 20px;min-height:auto;padding-bottom:80px}.bs-hero-grid{grid-template-columns:1fr;padding-top:42px;gap:35px}.bs-copy h1{font-size:48px}.bs-links{display:none}.bs-card{margin:0}.bs-tape{padding:34px 20px 60px}.bs-head,.bs-row{grid-template-columns:1.3fr 1fr .75fr}.bs-head>*:nth-child(3),.bs-row>*:nth-child(3),.bs-head>*:nth-child(4),.bs-row>*:nth-child(4){display:none}.bs-verify{padding:32px 20px}.bs-verify-inner{grid-template-columns:1fr;gap:20px}.bs-numbers{grid-template-columns:1fr}.bs-cell{border-right:0;border-bottom:1px solid var(--hair)}}
    `}</style>
    <section className="bs-hero">
      <nav className="bs-nav"><div className="bs-brand"><span className="bs-brand-mark"><span /><span /><span /></span>LumenMarc</div><div className="bs-links"><button className="active">Tape</button><button onClick={() => document.getElementById("bs-verify")?.scrollIntoView({ behavior: "smooth" })}>Verify</button><button>Portfolio</button><button>About</button></div><div className="bs-updated"><i />Snapshot ready</div></nav>
      <div className="bs-hero-grid">
        <div className="bs-copy"><div className="bs-kicker">Market integrity for tokenized stocks on Base</div><h1>See the difference before it matters.</h1><p>Every token&apos;s Chainlink reference and current pool price, measured in basis points and recorded directly from Base.</p><button className="bs-button" onClick={() => document.getElementById("bs-verify")?.scrollIntoView({ behavior: "smooth" })}>Verify a token or pool</button><div className="bs-meta">Block {snapshot.blockNumber.toLocaleString("en-US")} · captured {snapshot.capturedAtUtc.replace("T", " ").slice(0, 16)} UTC<br />{snapshot.market.reason}. Feeds are held at Friday&apos;s last print.</div></div>
        <article className="bs-card"><div className="bs-card-top"><div className="bs-token"><div className="bs-token-box">NV</div><div><strong>NVDAc</strong><small>NVIDIA Corporation · Aerodrome</small></div></div><span className="bs-source">Onchain price</span></div><div className="bs-numbers"><div className="bs-cell"><label>Reference price</label><output>{usd(snapshot.stocks[0].referencePrice, 4)}</output></div><div className="bs-cell"><label>Pool price</label><output>{usd(snapshot.stocks[0].onchainPrice, 3)}</output></div><div className="bs-cell"><label>Gap</label><output>{snapshot.stocks[0].premiumBps} bps</output></div></div><Plot /></article>
      </div>
    </section>
    <section className="bs-tape"><div className="bs-tape-head"><div><span className="bs-label">The tape</span><h2>All tokens at a glance.</h2></div><span className="bs-summary">{snapshot.tokensTotal} tokens · {snapshot.feeds.held} feeds held</span></div><div className="bs-table"><div className="bs-head"><span>Instrument</span><span>Reference</span><span>Onchain</span><span>Gap</span><span>State</span></div>{snapshot.stocks.map((stock) => <div className={`bs-row ${chosen.ticker === stock.ticker ? "selected" : ""}`} key={stock.ticker}><button onClick={() => setChosen(stock)}>{stock.ticker}<span>{stock.underlying}</span></button><span className="bs-value">{usd(stock.referencePrice)}</span><span className="bs-value">{usd(stock.onchainPrice)}</span><span className="bs-value">{stock.premiumBps === null ? "—" : `${stock.premiumBps > 0 ? "+" : ""}${stock.premiumBps} bps`}</span><Signal state={stock.state} /></div>)}</div></section>
    <section className="bs-verify" id="bs-verify"><div className="bs-verify-inner"><div><span className="bs-label">Source check</span><h2>Verify a token, pool, or wallet.</h2></div><div><form className="bs-form" onSubmit={(event) => { event.preventDefault(); setResult(results.length ? `${results[0].ticker} appears in this snapshot.` : "No snapshot match. Enter a token symbol or Base address."); }}><input aria-label="Token symbol or Base address" value={term} onChange={(event) => setTerm(event.target.value)} placeholder="Token symbol or Base address" /><button type="submit">Check snapshot</button></form><div className="bs-answer">{result}</div></div></div></section>
  </main>;
}