import { useMemo, useState } from "react";
import { snapshot } from "./_shared/snapshot";

const usd = (value: number | null, places = 2) => value === null ? "—" : value.toLocaleString("en-US", { style: "currency", currency: "USD", minimumFractionDigits: places, maximumFractionDigits: places });
const label = (state: string) => state[0].toUpperCase() + state.slice(1);

function LumenMark() {
  return <span className="es-mark" aria-hidden="true"><i /><i /></span>;
}

function Condition({ state }: { state: string }) {
  return <span className={`es-condition ${state}`}><i />{label(state)}</span>;
}

function Chart() {
  const series = snapshot.nvdaHistory;
  const ref = snapshot.stocks[0].referencePrice;
  const pools = series.map((item) => item.pool);
  const rawLow = Math.min(ref, ...pools);
  const rawHigh = Math.max(ref, ...pools);
  const padding = (rawHigh - rawLow) * 0.95;
  const low = rawLow - padding;
  const high = rawHigh + padding;
  const width = 800, height = 270, yPad = 18;
  const y = (v: number) => yPad + (high - v) / (high - low) * (height - 2 * yPad);
  const path = pools.map((v, idx) => `${(idx / (pools.length - 1) * width).toFixed(1)},${y(v).toFixed(1)}`).join(" ");
  return <div className="es-chart">
    <div className="es-legend"><span><i className="es-pool" />Pool price</span><span><i className="es-reference" />Reference</span></div>
    <svg viewBox={`0 0 ${width} ${height}`} preserveAspectRatio="none" role="img" aria-label="NVDAc 24 hour onchain and reference price series">
      {[.2,.5,.8].map((line) => <line key={line} x1="0" x2={width} y1={height * line} y2={height * line} className="es-grid-line" />)}
      <line x1="0" x2={width} y1={y(ref)} y2={y(ref)} className="es-ref" />
      <polyline points={path} className="es-pool-path" />
      <circle cx={width} cy={y(pools[pools.length - 1])} r="4.5" className="es-last" />
    </svg>
    <div className="es-times"><span>15:20 UTC</span><span>18:30</span><span>21:03</span></div>
  </div>;
}

export function ExchangeSans() {
  const [activeTicker, setActiveTicker] = useState("NVDAc");
  const [verify, setVerify] = useState(false);
  const [term, setTerm] = useState("");
  const active = useMemo(() => snapshot.stocks.find((item) => item.ticker === activeTicker) ?? snapshot.stocks[0], [activeTicker]);
  const results = useMemo(() => snapshot.stocks.filter((item) => `${item.ticker} ${item.name} ${item.address}`.toLowerCase().includes(term.toLowerCase())), [term]);
  return <main className="exchange-sans">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Manrope:wght@400;500;600;700;800&display=swap" />
    <style>{`
      .exchange-sans{--ink:#111d3b;--sub:#63708c;--base:#2457f5;--pale:#f5f7ff;--paper:#fcfcfa;--line:#dfe3ee;--good:#1e7869;--warn:#a75d18;--bad:#b84740;min-height:100dvh;background:var(--paper);color:var(--ink);font-family:Manrope,sans-serif;letter-spacing:-.035em}.exchange-sans *{box-sizing:border-box}.exchange-sans button,.exchange-sans input{font:inherit}.es-wrap{max-width:1200px;margin:auto;padding:0 32px}.es-nav{height:84px;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;border-bottom:1px solid var(--line)}.es-brand{font-weight:800;font-size:18px;display:inline-flex;align-items:center;gap:9px;letter-spacing:-.065em}.es-mark{height:17px;width:17px;display:inline-grid;grid-template-columns:1fr 1fr;gap:3px;align-items:end}.es-mark i{background:var(--base);height:17px}.es-mark i+ i{height:10px}.es-nav-links{display:flex;gap:29px;height:84px;align-items:center}.es-nav-links button{height:100%;border:0;background:none;color:var(--sub);font-size:13px;cursor:pointer;padding:2px 0 0}.es-nav-links button:first-child{color:var(--ink);font-weight:800;border-bottom:2px solid var(--base)}.es-verify-button{justify-self:end;border:1px solid var(--ink);background:var(--ink);color:#fff;padding:9px 13px;border-radius:4px;font-size:12px;font-weight:700;cursor:pointer;transition:transform .18s ease,background .18s ease}.es-verify-button:hover{transform:translateY(-1px);background:var(--base);border-color:var(--base)}
      .es-intro{padding:51px 0 37px;display:flex;justify-content:space-between;align-items:end}.es-intro h1{font-size:41px;line-height:1.05;letter-spacing:-.07em;max-width:720px;margin:0;font-weight:800}.es-intro h1 span{color:var(--base)}.es-intro p{color:var(--sub);font-size:13px;line-height:1.55;max-width:285px;margin:0}.es-instrument{border:1px solid var(--line);background:white}.es-instrument-head{padding:20px 25px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--line)}.es-symbol{display:flex;align-items:baseline;gap:12px}.es-symbol strong{font-size:22px;letter-spacing:-.06em}.es-symbol span{font-size:12px;color:var(--sub)}.es-read{font-family:"DM Mono",monospace;font-size:10px;color:var(--sub);letter-spacing:-.03em}.es-read b{font-weight:500;color:var(--ink)}.es-data{display:grid;grid-template-columns:1fr 1fr .84fr}.es-stat{min-height:138px;padding:23px 25px;border-right:1px solid var(--line)}.es-stat:last-child{border:0}.es-kicker{font-family:"DM Mono",monospace;color:var(--sub);font-size:10px;letter-spacing:.02em;text-transform:uppercase;display:block;margin-bottom:11px}.es-number{font-size:34px;letter-spacing:-.075em;font-weight:700;line-height:1}.es-number.gap{color:var(--base)}.es-stat small{display:block;font-size:11px;color:var(--sub);margin-top:12px;letter-spacing:-.02em}.es-condition{font-size:12px;font-weight:700;display:flex;align-items:center;gap:7px}.es-condition i{display:block;height:7px;width:7px;border-radius:50%;background:var(--good)}.es-condition.elevated{color:var(--warn)}.es-condition.elevated i{background:var(--warn)}.es-condition.dislocated{color:var(--bad)}.es-condition.dislocated i{background:var(--bad)}.es-condition.unpriced{color:var(--sub)}.es-condition.unpriced i{background:#a5adbb}
      .es-history{padding:25px 25px 18px;border-top:1px solid var(--line)}.es-history-top{display:flex;justify-content:space-between;align-items:center;margin-bottom:13px}.es-history-title{font-size:13px;font-weight:800}.es-history-note{font-size:11px;color:var(--sub)}.es-chart{position:relative}.es-legend{display:flex;justify-content:flex-end;gap:18px;font-size:10px;color:var(--sub);margin-bottom:8px}.es-legend span{display:flex;align-items:center;gap:6px}.es-legend i{display:block;width:17px;height:2px}.es-pool{background:var(--base)}.es-reference{background:var(--ink);opacity:.5}.es-chart svg{height:270px;width:100%;display:block}.es-grid-line{stroke:#e9ecf3;stroke-width:1}.es-ref{stroke:var(--ink);stroke-width:1;stroke-dasharray:4 5;opacity:.48}.es-pool-path{fill:none;stroke:var(--base);stroke-width:2.25;stroke-linejoin:round;stroke-linecap:round}.es-last{fill:#fff;stroke:var(--base);stroke-width:2}.es-times{font-family:"DM Mono",monospace;display:flex;justify-content:space-between;color:#8993a8;font-size:10px;margin-top:1px}
      .es-tape{border:1px solid var(--line);border-top:0;background:var(--pale)}.es-tape-head,.es-row{display:grid;grid-template-columns:1.13fr .9fr .9fr .55fr .67fr;align-items:center;padding:0 25px}.es-tape-head{height:55px;border-bottom:1px solid var(--line)}.es-tape-head h2{font-size:13px;letter-spacing:-.04em;margin:0}.es-tape-head p{grid-column:2 / -1;text-align:right;color:var(--sub);font-size:11px;margin:0}.es-row{width:100%;height:52px;border:0;border-bottom:1px solid var(--line);background:transparent;text-align:left;color:var(--ink);cursor:pointer;transition:background .16s ease}.es-row:last-child{border-bottom:0}.es-row:hover,.es-row.current{background:#fff}.es-ticker{font-size:13px;font-weight:800}.es-ticker em{font-style:normal;font-weight:500;color:var(--sub);font-size:11px;margin-left:7px}.es-cell{font-family:"DM Mono",monospace;font-size:11px;letter-spacing:-.04em}.es-muted{color:var(--sub)}.es-footer{font-size:11px;color:var(--sub);padding:20px 0 42px;display:flex;justify-content:space-between}.es-dim{position:fixed;inset:0;background:rgba(17,29,59,.16);z-index:5;display:flex;justify-content:flex-end}.es-drawer{width:min(466px,100vw);height:100%;padding:28px;background:#fff;box-shadow:-12px 0 32px rgba(18,34,76,.1);animation:es-slide .2s ease}.es-drawer-top{display:flex;justify-content:space-between;align-items:center}.es-close{background:none;border:0;font-size:21px;cursor:pointer}.es-drawer h2{font-size:31px;letter-spacing:-.065em;line-height:1.05;margin:47px 0 9px}.es-drawer p{color:var(--sub);font-size:13px;line-height:1.55;max-width:330px}.es-search{width:100%;border:1px solid var(--line);padding:14px;margin:21px 0 8px;outline:none;font-size:13px}.es-search:focus{border-color:var(--base)}.es-result{width:100%;border:0;border-bottom:1px solid var(--line);padding:13px 0;background:none;text-align:left;cursor:pointer;color:var(--ink)}.es-result strong{font-size:13px;display:block}.es-result span{font-family:"DM Mono",monospace;font-size:10px;color:var(--sub)}.es-result:hover strong{color:var(--base)}@keyframes es-slide{from{transform:translateX(18px);opacity:0}to{transform:translateX(0);opacity:1}}
      @media(max-width:720px){.es-wrap{padding:0 16px}.es-nav{height:68px;grid-template-columns:1fr auto}.es-nav-links{display:none}.es-intro{padding:35px 0 27px;display:block}.es-intro h1{font-size:32px}.es-intro p{margin-top:14px}.es-read{display:none}.es-instrument-head,.es-history{padding-left:16px;padding-right:16px}.es-data{grid-template-columns:1fr 1fr}.es-stat{padding:18px 16px;min-height:122px}.es-stat:nth-child(2){border-right:0}.es-stat:nth-child(3){grid-column:span 2;border-top:1px solid var(--line);min-height:auto}.es-number{font-size:26px}.es-history-note{display:none}.es-row{padding:0 16px;grid-template-columns:1fr 1fr .8fr}.es-row .es-cell:nth-child(3),.es-row .es-cell:nth-child(4){display:none}.es-tape-head{padding:0 16px;display:flex;justify-content:space-between}.es-tape-head p{display:none}.es-footer{display:block}.es-footer span+span{display:block;margin-top:5px}}
    `}</style>
    <div className="es-wrap">
      <nav className="es-nav"><div className="es-brand"><LumenMark />LumenMarc</div><div className="es-nav-links"><button type="button">Tape</button><button type="button" onClick={() => setVerify(true)}>Verify</button><button type="button">Portfolio</button><button type="button">About</button></div><button className="es-verify-button" type="button" onClick={() => setVerify(true)}>Verify an address</button></nav>
      <header className="es-intro"><h1>Read the <span>price gap</span> before you trade.</h1><p>LumenMarc checks the reference feed against the onchain pool price for tokenized equities on Base.</p></header>
      <section className="es-instrument"><div className="es-instrument-head"><div className="es-symbol"><strong>{active.ticker}</strong><span>{active.name}</span></div><div className="es-read">Base block <b>{snapshot.blockNumber.toLocaleString()}</b> · captured 21:03 UTC</div></div>
      <div className="es-data"><div className="es-stat"><span className="es-kicker">Chainlink reference</span><div className="es-number">{usd(active.referencePrice, active.referencePrice < 200 ? 4 : 2)}</div><small>Held at Friday’s last print</small></div><div className="es-stat"><span className="es-kicker">Onchain pool price</span><div className="es-number">{usd(active.onchainPrice)}</div><small>{active.venue ? `${active.venue} · ${active.quote}` : "No USD quote available"}</small></div><div className="es-stat"><span className="es-kicker">Price gap</span><div className="es-number gap">{active.premiumBps === null ? "—" : `${active.premiumBps > 0 ? "+" : ""}${active.premiumBps} bps`}</div><small><Condition state={active.state} /></small></div></div>
      {active.ticker === "NVDAc" ? <div className="es-history"><div className="es-history-top"><span className="es-history-title">NVDAc pool price · last 24 hours</span><span className="es-history-note">US market closed · reference remains held</span></div><Chart /></div> : <div className="es-history"><div className="es-history-top"><span className="es-history-title">{active.ticker} selected from the tape</span><button type="button" className="es-verify-button" onClick={() => setVerify(true)}>Verify this asset</button></div><div style={{height:270,display:"grid",placeItems:"center",borderTop:"1px solid var(--line)",color:"var(--sub)",fontSize:13}}>The captured history series is available for NVDAc.</div></div>}</section>
      <section className="es-tape"><div className="es-tape-head"><h2>Covered tokens</h2><p>{snapshot.tokensTotal} assets · snapshot at block {snapshot.blockNumber.toLocaleString()}</p></div>{snapshot.stocks.map((item) => <button type="button" key={item.ticker} className={`es-row ${active.ticker === item.ticker ? "current" : ""}`} onClick={() => setActiveTicker(item.ticker)}><span className="es-ticker">{item.ticker}<em>{item.underlying}</em></span><span className="es-cell">{usd(item.referencePrice, item.referencePrice < 200 ? 4 : 2)}</span><span className={`es-cell ${item.onchainPrice === null ? "es-muted" : ""}`}>{usd(item.onchainPrice)}</span><span className={`es-cell ${item.premiumBps === null ? "es-muted" : ""}`}>{item.premiumBps === null ? "—" : `${item.premiumBps > 0 ? "+" : ""}${item.premiumBps}`}</span><Condition state={item.state} /></button>)}</section>
      <footer className="es-footer"><span>Informational only. Not investment advice.</span><span>{snapshot.market.reason}. Reference feeds are held at Friday’s last print.</span></footer>
    </div>
    {verify && <div className="es-dim" role="dialog" aria-label="Verify token or address" aria-modal="true"><aside className="es-drawer"><div className="es-drawer-top"><div className="es-brand"><LumenMark />LumenMarc</div><button className="es-close" type="button" onClick={() => setVerify(false)} aria-label="Close verification">×</button></div><h2>Verify an address</h2><p>Search the supported token contracts in this captured market snapshot.</p><input autoFocus className="es-search" value={term} onChange={(event) => setTerm(event.target.value)} placeholder="Token name or contract address" />{results.map((item) => <button type="button" className="es-result" key={item.ticker} onClick={() => { setActiveTicker(item.ticker); setVerify(false); }}><strong>{item.ticker} · {item.name}</strong><span>{item.address}</span></button>)}</aside></div>}
  </main>;
}