import { useMemo, useState } from "react";
import { snapshot } from "./_shared/snapshot";

const money = (value: number | null, digits = 2) =>
  value === null ? "—" : value.toLocaleString("en-US", { style: "currency", currency: "USD", minimumFractionDigits: digits, maximumFractionDigits: digits });

const stateLabel = (state: string) => state === "unpriced" ? "Unpriced" : state[0].toUpperCase() + state.slice(1);

function Mark() {
  return <span className="lm-mark" aria-hidden="true"><i /><i /><i /></span>;
}

function State({ state }: { state: string }) {
  return <span className={`lm-state ${state}`}><b />{stateLabel(state)}</span>;
}

function PriceChart() {
  const points = snapshot.nvdaHistory;
  const pools = points.map((point) => point.pool);
  const min = Math.min(snapshot.stocks[0].referencePrice, ...pools) - 0.15;
  const max = Math.max(snapshot.stocks[0].referencePrice, ...pools) + 0.15;
  const w = 740, h = 226, inset = 13;
  const pointString = pools.map((value, index) => {
    const x = (index / (pools.length - 1)) * w;
    const y = inset + (max - value) / (max - min) * (h - inset * 2);
    return `${x.toFixed(1)},${y.toFixed(1)}`;
  }).join(" ");
  const refY = inset + (max - snapshot.stocks[0].referencePrice) / (max - min) * (h - inset * 2);
  return <div className="lm-chart-wrap">
    <div className="lm-chart-key"><span><i className="pool-line" />Pool price</span><span><i className="ref-line" />Reference</span></div>
    <svg className="lm-chart" viewBox={`0 0 ${w} ${h}`} preserveAspectRatio="none" role="img" aria-label="NVDAc pool price history compared to reference price">
      <line x1="0" y1={refY} x2={w} y2={refY} className="reference" />
      <polyline points={pointString} className="pool" />
      <circle cx={w} cy={Number(pointString.split(" ").at(-1)?.split(",")[1])} r="4" className="last" />
    </svg>
    <div className="lm-chart-times"><span>15:20 UTC</span><span>18:30</span><span>21:03</span></div>
  </div>;
}

export function Exchange() {
  const [selected, setSelected] = useState("NVDAc");
  const [verifyOpen, setVerifyOpen] = useState(false);
  const [query, setQuery] = useState("");
  const active = useMemo(() => snapshot.stocks.find((stock) => stock.ticker === selected) ?? snapshot.stocks[0], [selected]);
  const matches = useMemo(() => snapshot.stocks.filter((stock) => `${stock.ticker} ${stock.name} ${stock.address}`.toLowerCase().includes(query.toLowerCase())), [query]);

  return <main className="lumen-exchange">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Manrope:wght@400;500;600;700&family=Newsreader:opsz,wght@6..72,500;6..72,600&display=swap" />
    <style>{`
      .lumen-exchange{--ink:#17252c;--muted:#637176;--paper:#f4f2ed;--sheet:#fbfaf7;--rule:#d9dad3;--mint:#267466;--amber:#ad6d1c;--red:#ad4f45;min-height:100dvh;background:var(--paper);color:var(--ink);font-family:Manrope,sans-serif;letter-spacing:-.015em}
      .lumen-exchange *{box-sizing:border-box}.lumen-exchange button,.lumen-exchange input{font:inherit}.lm-shell{max-width:1188px;margin:auto;padding:0 28px}.lm-nav{height:82px;border-bottom:1px solid var(--rule);display:flex;align-items:center;justify-content:space-between}.lm-brand{display:flex;gap:11px;align-items:center;font-size:18px;font-weight:700;letter-spacing:-.055em}.lm-mark{display:inline-flex;gap:2px;height:19px;align-items:flex-end}.lm-mark i{display:block;width:4px;background:var(--ink)}.lm-mark i:nth-child(1){height:8px}.lm-mark i:nth-child(2){height:14px}.lm-mark i:nth-child(3){height:19px}.lm-links{display:flex;height:100%;align-items:center;gap:28px}.lm-links button,.lm-verify-link{border:0;background:none;color:var(--muted);font-size:13px;cursor:pointer;padding:7px 0}.lm-links button:first-child{color:var(--ink);font-weight:700;border-bottom:2px solid var(--ink);height:100%;padding-top:9px}.lm-verify-link{color:var(--ink);font-weight:700;border-bottom:1px solid var(--ink)}
      .lm-intro{display:grid;grid-template-columns:1fr auto;align-items:end;padding:48px 0 28px}.lm-eyebrow{font-family:"DM Mono",monospace;color:var(--muted);font-size:11px;letter-spacing:.01em;margin-bottom:12px}.lm-intro h1{font-family:Newsreader,serif;font-weight:500;font-size:40px;line-height:1.04;letter-spacing:-.045em;margin:0;max-width:580px}.lm-intro p{font-size:13px;color:var(--muted);max-width:317px;line-height:1.55;margin:0}.lm-instrument{background:var(--sheet);border:1px solid var(--rule);border-bottom:0}.lm-instrument-head{height:72px;padding:0 28px;border-bottom:1px solid var(--rule);display:flex;align-items:center;justify-content:space-between}.lm-asset{display:flex;align-items:baseline;gap:10px}.lm-asset strong{font-size:23px;letter-spacing:-.055em}.lm-asset span{color:var(--muted);font-size:13px}.lm-snapshot{font-family:"DM Mono",monospace;font-size:11px;color:var(--muted)}.lm-snapshot b{color:var(--ink);font-weight:500}
      .lm-quote{display:grid;grid-template-columns:1.15fr 1fr .72fr;border-bottom:1px solid var(--rule)}.lm-value{padding:25px 28px 23px;border-right:1px solid var(--rule)}.lm-value:last-child{border:0}.lm-label{font-family:"DM Mono",monospace;text-transform:uppercase;letter-spacing:.035em;color:var(--muted);font-size:10px;display:block;margin-bottom:9px}.lm-price{font-size:29px;letter-spacing:-.055em;font-weight:600}.lm-gap{font-size:29px;letter-spacing:-.055em;color:var(--amber);font-weight:600}.lm-value small{font-size:11px;color:var(--muted);margin-top:8px;display:block}.lm-state{display:flex;align-items:center;gap:7px;font-size:14px;font-weight:600}.lm-state b{width:7px;height:7px;border-radius:50%;background:var(--mint)}.lm-state.elevated{color:var(--amber)}.lm-state.elevated b{background:var(--amber)}.lm-state.dislocated{color:var(--red)}.lm-state.dislocated b{background:var(--red)}.lm-state.unpriced{color:var(--muted)}.lm-state.unpriced b{background:#a9b0ad}
      .lm-chart-panel{padding:21px 28px 17px}.lm-chart-top{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px}.lm-chart-title{font-size:13px;font-weight:700}.lm-chart-note{color:var(--muted);font-size:11px}.lm-chart-wrap{position:relative}.lm-chart-key{display:flex;justify-content:flex-end;gap:17px;font-size:10px;color:var(--muted);margin:-2px 0 8px}.lm-chart-key span{display:flex;align-items:center;gap:5px}.lm-chart-key i{width:16px;height:2px;display:block}.pool-line{background:var(--ink)}.ref-line{background:var(--amber);opacity:.7}.lm-chart{width:100%;height:226px;overflow:visible;background:repeating-linear-gradient(to bottom,transparent 0,transparent 55px,#e6e5df 56px)}.lm-chart .pool{fill:none;stroke:var(--ink);stroke-width:2.1;stroke-linejoin:round;stroke-linecap:round}.lm-chart .reference{stroke:var(--amber);stroke-width:1.25;stroke-dasharray:4 4;opacity:.8}.lm-chart .last{fill:var(--sheet);stroke:var(--ink);stroke-width:2}.lm-chart-times{display:flex;justify-content:space-between;color:#8b9492;font-family:"DM Mono",monospace;font-size:10px;margin-top:1px}
      .lm-tape{border:1px solid var(--rule);border-top:0;background:#eeece6}.lm-tape-head{padding:17px 28px 13px;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid var(--rule)}.lm-tape-head h2{font-size:14px;margin:0;letter-spacing:-.03em}.lm-tape-head p{margin:0;color:var(--muted);font-size:11px}.lm-token-row{display:grid;grid-template-columns:1.15fr .88fr .88fr .57fr .7fr;align-items:center;width:100%;border:0;border-bottom:1px solid var(--rule);background:transparent;padding:13px 28px;text-align:left;cursor:pointer;color:var(--ink);transition:background .18s ease}.lm-token-row:hover,.lm-token-row.selected{background:var(--sheet)}.lm-token-row:last-child{border-bottom:0}.lm-token{font-size:13px;font-weight:700}.lm-token small{font-weight:400;color:var(--muted);margin-left:8px}.lm-cell{font-family:"DM Mono",monospace;font-size:11px;color:var(--ink);letter-spacing:-.03em}.lm-cell.muted{color:var(--muted)}
      .lm-foot{padding:20px 0 42px;color:var(--muted);font-size:11px;line-height:1.5;display:flex;justify-content:space-between;gap:24px}.lm-foot span:last-child{text-align:right}.lm-verify{position:fixed;inset:0;background:rgba(23,37,44,.16);display:flex;justify-content:flex-end;z-index:5}.lm-drawer{width:min(470px,100%);height:100%;background:var(--sheet);border-left:1px solid var(--rule);padding:28px;box-shadow:-12px 0 35px rgba(23,37,44,.08);animation:lm-in .22s ease}.lm-drawer-top{display:flex;justify-content:space-between;align-items:center}.lm-drawer h2{font-family:Newsreader,serif;font-size:30px;font-weight:500;letter-spacing:-.04em;margin:42px 0 9px}.lm-drawer p{color:var(--muted);font-size:13px;line-height:1.6;max-width:340px}.lm-close{border:0;background:none;font-size:20px;cursor:pointer;color:var(--ink)}.lm-search{width:100%;border:1px solid var(--rule);background:var(--paper);padding:14px;margin:22px 0 10px;font-size:13px;outline:none}.lm-search:focus{border-color:var(--ink)}.lm-result{display:block;width:100%;border:0;border-bottom:1px solid var(--rule);background:none;padding:12px 0;text-align:left;cursor:pointer;font-size:13px}.lm-result strong{display:block}.lm-result span{font-family:"DM Mono",monospace;color:var(--muted);font-size:10px}.lm-result:hover strong{color:var(--mint)}@keyframes lm-in{from{transform:translateX(22px);opacity:0}to{transform:translateX(0);opacity:1}}
      @media(max-width:700px){.lm-shell{padding:0 16px}.lm-nav{height:66px}.lm-links{gap:15px}.lm-links button:nth-child(n+3){display:none}.lm-intro{display:block;padding:32px 0 23px}.lm-intro h1{font-size:32px}.lm-intro p{margin-top:14px}.lm-snapshot{display:none}.lm-quote{grid-template-columns:1fr 1fr}.lm-value{padding:19px 16px}.lm-value:nth-child(2){border-right:0}.lm-value:nth-child(3){border-top:1px solid var(--rule);grid-column:span 2}.lm-instrument-head,.lm-chart-panel,.lm-tape-head{padding-left:16px;padding-right:16px}.lm-price,.lm-gap{font-size:22px}.lm-token-row{padding:12px 16px;grid-template-columns:1fr .8fr .65fr}.lm-token-row .lm-cell:nth-child(3),.lm-token-row .lm-cell:nth-child(4){display:none}.lm-foot{display:block}.lm-foot span:last-child{text-align:left;display:block;margin-top:6px}}
    `}</style>
    <div className="lm-shell">
      <nav className="lm-nav"><div className="lm-brand"><Mark />LumenMarc</div><div className="lm-links"><button type="button">Tape</button><button type="button" onClick={() => setVerifyOpen(true)}>Verify</button><button type="button">Portfolio</button><button type="button">About</button></div><button className="lm-verify-link" type="button" onClick={() => setVerifyOpen(true)}>Verify an address</button></nav>
      <section className="lm-intro"><div><div className="lm-eyebrow">BASE / TOKENIZED EQUITIES</div><h1>Market integrity, read directly from the chain.</h1></div><p>Reference feeds and executable pool prices, kept in their proper relation.</p></section>
      <section className="lm-instrument" aria-label="Featured NVDAc market">
        <div className="lm-instrument-head"><div className="lm-asset"><strong>{active.ticker}</strong><span>{active.name}</span></div><div className="lm-snapshot">Base block <b>{snapshot.blockNumber.toLocaleString()}</b> · captured 21:03 UTC</div></div>
        <div className="lm-quote"><div className="lm-value"><span className="lm-label">Chainlink reference</span><div className="lm-price">{money(active.referencePrice, active.referencePrice < 200 ? 4 : 2)}</div><small>{active.feedState === "held" ? "Held at Friday's last print" : "Current reference"}</small></div><div className="lm-value"><span className="lm-label">Onchain pool price</span><div className="lm-price">{money(active.onchainPrice)}</div><small>{active.venue ? `${active.venue} · ${active.quote}` : "No USD pool quote"}</small></div><div className="lm-value"><span className="lm-label">Price gap</span><div className="lm-gap">{active.premiumBps === null ? "—" : `${active.premiumBps > 0 ? "+" : ""}${active.premiumBps} bps`}</div><small><State state={active.state} /></small></div></div>
        {active.ticker === "NVDAc" ? <div className="lm-chart-panel"><div className="lm-chart-top"><span className="lm-chart-title">Pool price / 24 hours</span><span className="lm-chart-note">Reference is flat while US markets are closed</span></div><PriceChart /></div> : <div className="lm-chart-panel"><div className="lm-chart-top"><span className="lm-chart-title">Selected from tape</span><button className="lm-verify-link" type="button" onClick={() => setVerifyOpen(true)}>Inspect {active.ticker}</button></div><div style={{height: 226, display:"grid", placeItems:"center", borderTop:"1px solid var(--rule)", color:"var(--muted)", fontSize:13}}>Historical pool series is shown for NVDAc in this snapshot.</div></div>}
      </section>
      <section className="lm-tape"><div className="lm-tape-head"><h2>Coverage tape</h2><p>{snapshot.tokensTotal} tokenized equities · held feeds shown as captured</p></div>{snapshot.stocks.map((stock) => <button key={stock.ticker} type="button" className={`lm-token-row ${stock.ticker === active.ticker ? "selected" : ""}`} onClick={() => setSelected(stock.ticker)}><span className="lm-token">{stock.ticker}<small>{stock.underlying}</small></span><span className="lm-cell">{money(stock.referencePrice, stock.referencePrice < 200 ? 4 : 2)}</span><span className={`lm-cell ${stock.onchainPrice === null ? "muted" : ""}`}>{money(stock.onchainPrice)}</span><span className={`lm-cell ${stock.premiumBps === null ? "muted" : ""}`}>{stock.premiumBps === null ? "—" : `${stock.premiumBps > 0 ? "+" : ""}${stock.premiumBps}`}</span><span><State state={stock.state} /></span></button>)}</section>
      <footer className="lm-foot"><span>Informational only. Not investment advice.</span><span>{snapshot.market.reason}. All reference feeds are held at Friday’s last print.</span></footer>
    </div>
    {verifyOpen && <div className="lm-verify" role="dialog" aria-modal="true" aria-label="Verify a token"><div className="lm-drawer"><div className="lm-drawer-top"><div className="lm-brand"><Mark />LumenMarc</div><button className="lm-close" type="button" onClick={() => setVerifyOpen(false)} aria-label="Close">×</button></div><h2>Verify an address</h2><p>Find a supported token, pool, or wallet against this captured market snapshot.</p><input className="lm-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Paste or search an address" autoFocus />{matches.map((stock) => <button type="button" className="lm-result" key={stock.ticker} onClick={() => { setSelected(stock.ticker); setVerifyOpen(false); }}><strong>{stock.ticker} · {stock.name}</strong><span>{stock.address}</span></button>)}</div></div>}
  </main>;
}