// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/lumenmarc-hero/BaseBlue.tsx": () => import("../components/mockups/lumenmarc-hero/BaseBlue.tsx"),
  "./components/mockups/lumenmarc-hero/BaseBlueSans.tsx": () => import("../components/mockups/lumenmarc-hero/BaseBlueSans.tsx"),
  "./components/mockups/lumenmarc-hero/Exchange.tsx": () => import("../components/mockups/lumenmarc-hero/Exchange.tsx"),
  "./components/mockups/lumenmarc-hero/ExchangeSans.tsx": () => import("../components/mockups/lumenmarc-hero/ExchangeSans.tsx"),
  "./components/mockups/lumenmarc-hero/NightDesk.tsx": () => import("../components/mockups/lumenmarc-hero/NightDesk.tsx"),
  "./components/mockups/lumenmarc-hero/Prospectus.tsx": () => import("../components/mockups/lumenmarc-hero/Prospectus.tsx")
};
